### ISSUE TITLE
is.promise  to check promise object

### ISSUE THREAD

**Issue by nnn-gif** [scottrabin/is-js#16]
is.promise  to check promise object

**Comment by scottrabin** [comment]
Hi @niktrix! Apologies - Github seems to not want to send emails to notify me when issues are opened.

I'd be happy to accept a PR on this. Just make sure the function returns `true` for Promises-compliant libraries (e.g. es6-promise or bluebird) as well as the native `Promise` object (if it exists, of course).

It may be a bit until I can get to it myself, unfortunately.

**Comment by scottrabin** [comment]
Took care of it in 0.2.1, many, _many_ years later.
